// "Como foi feito" — transparency page about how Farol was created.
// Discloses the human direction / AI assistance split and the informational
// (non-clinical) scope, consistent with the manual's own Ética & RGPD guidance.
// One entry per language.
//
// Only state here what is actually true of the process. Claims about review
// rounds or native verification do not belong unless that review happened and
// the author can vouch for it.
import { ALL_LANGS, type Lang } from './i18n';

export interface MadePage {
  title: string;      // page + footer link title
  cat: string;        // card category stamp
  subtitle: string;
  desc: string;       // meta description
  items: string[];    // six disclosure bullets (HTML allowed)
  etica: string;      // label prefix for the Ética & RGPD link row
}

export const made: Record<Lang, MadePage> = {
  pt: {
    title: 'Como foi feito',
    cat: 'Transparência',
    subtitle: 'Direção humana e assistência de IA — quem fez o quê.',
    desc: 'Transparência sobre o processo de criação do Farol: direção humana e assistência de IA.',
    items: [
      '<strong>Conceção, direção e estrutura pedagógica:</strong> Guilherme de Góis Machado.',
      'O conteúdo foi redigido com assistência de IA (Claude, da Anthropic) sob direção do autor.',
      'Cada cartão indica as fontes em que se apoia; a maioria inclui ligação direta ao original.',
      'As traduções foram geradas com IA.',
      '<strong>Porquê divulgar?</strong> Por coerência com a orientação de Ética & RGPD do próprio manual: a transparência sobre o uso de IA é precisamente o que o Farol recomenda aos docentes.',
      'O Farol é um recurso informativo, não orientação clínica: a identificação e o diagnóstico cabem a profissionais qualificados.',
    ],
    etica: 'Ver também',
  },
  en: {
    title: 'How it was made',
    cat: 'Transparency',
    subtitle: 'Human direction and AI assistance — who did what.',
    desc: 'Transparency about how Farol was created: human direction and AI assistance.',
    items: [
      '<strong>Conception, direction and pedagogical structure:</strong> Guilherme de Góis Machado.',
      'The content was drafted with AI assistance (Claude, by Anthropic) under the author’s direction.',
      'Each card lists the sources it draws on; most include a direct link to the original.',
      'The translations were generated with AI.',
      '<strong>Why disclose?</strong> For consistency with the manual’s own Ethics & GDPR guidance: transparency about AI use is precisely what Farol recommends to teachers.',
      'Farol is an informational resource, not clinical guidance: identification and diagnosis belong to qualified professionals.',
    ],
    etica: 'See also',
  },
  es: {
    title: 'Cómo se hizo',
    cat: 'Transparencia',
    subtitle: 'Dirección humana y asistencia de IA: quién hizo qué.',
    desc: 'Transparencia sobre el proceso de creación de Farol: dirección humana y asistencia de IA.',
    items: [
      '<strong>Concepción, dirección y estructura pedagógica:</strong> Guilherme de Góis Machado.',
      'El contenido se redactó con asistencia de IA (Claude, de Anthropic) bajo la dirección del autor.',
      'Cada ficha indica las fuentes en las que se apoya; la mayoría incluye un enlace directo al original.',
      'Las traducciones se generaron con IA.',
      '<strong>¿Por qué divulgarlo?</strong> Por coherencia con la propia guía de Ética y RGPD del manual: la transparencia sobre el uso de la IA es precisamente lo que Farol recomienda al profesorado.',
      'Farol es un recurso informativo, no una orientación clínica: la identificación y el diagnóstico corresponden a profesionales cualificados.',
    ],
    etica: 'Ver también',
  },
  fr: {
    title: 'Comment il a été fait',
    cat: 'Transparence',
    subtitle: 'Direction humaine et assistance de l’IA — qui a fait quoi.',
    desc: 'Transparence sur la création de Farol : direction humaine et assistance de l’IA.',
    items: [
      '<strong>Conception, direction et structure pédagogique :</strong> Guilherme de Góis Machado.',
      'Le contenu a été rédigé avec l’assistance d’une IA (Claude, d’Anthropic) sous la direction de l’auteur.',
      'Chaque fiche indique les sources sur lesquelles elle s’appuie ; la plupart comportent un lien direct vers l’original.',
      'Les traductions ont été générées par IA.',
      '<strong>Pourquoi le dire ?</strong> Par cohérence avec les repères Éthique & RGPD du manuel lui-même : la transparence sur l’usage de l’IA est précisément ce que Farol recommande aux enseignants.',
      'Farol est une ressource d’information, pas un guide clinique : l’identification et le diagnostic relèvent de professionnels qualifiés.',
    ],
    etica: 'Voir aussi',
  },
  it: {
    title: 'Come è stato fatto',
    cat: 'Trasparenza',
    subtitle: 'Direzione umana e assistenza dell’IA — chi ha fatto cosa.',
    desc: 'Trasparenza sul processo di creazione di Farol: direzione umana e assistenza dell’IA.',
    items: [
      '<strong>Concezione, direzione e struttura pedagogica:</strong> Guilherme de Góis Machado.',
      'I contenuti sono stati redatti con l’assistenza di un’IA (Claude, di Anthropic) sotto la direzione dell’autore.',
      'Ogni scheda indica le fonti su cui si basa; la maggior parte include un link diretto all’originale.',
      'Le traduzioni sono state generate con l’IA.',
      '<strong>Perché dichiararlo?</strong> Per coerenza con le indicazioni di Etica & GDPR del manuale stesso: la trasparenza sull’uso dell’IA è esattamente ciò che Farol raccomanda ai docenti.',
      'Farol è una risorsa informativa, non una guida clinica: identificazione e diagnosi spettano a professionisti qualificati.',
    ],
    etica: 'Vedi anche',
  },
  hr: {
    title: 'Kako je nastao',
    cat: 'Transparentnost',
    subtitle: 'Ljudsko vodstvo i pomoć umjetne inteligencije — tko je što radio.',
    desc: 'Transparentnost o nastanku Farola: ljudsko vodstvo i pomoć umjetne inteligencije.',
    items: [
      '<strong>Koncepcija, vodstvo i pedagoška struktura:</strong> Guilherme de Góis Machado.',
      'Sadržaj je izrađen uz pomoć umjetne inteligencije (Claude, tvrtke Anthropic) pod vodstvom autora.',
      'Svaka kartica navodi izvore na kojima se temelji; većina sadrži izravnu poveznicu na izvornik.',
      'Prijevodi su generirani umjetnom inteligencijom.',
      '<strong>Zašto to objaviti?</strong> Radi dosljednosti sa smjernicama Etike i GDPR-a samog priručnika: transparentnost o korištenju UI upravo je ono što Farol preporučuje nastavnicima.',
      'Farol je informativni resurs, a ne kliničke smjernice: identifikacija i dijagnoza pripadaju kvalificiranim stručnjacima.',
    ],
    etica: 'Vidi također',
  },
  de: {
    title: 'Wie es entstanden ist',
    cat: 'Transparenz',
    subtitle: 'Menschliche Leitung und KI-Unterstützung — wer was gemacht hat.',
    desc: 'Transparenz über die Entstehung von Farol: menschliche Leitung und KI-Unterstützung.',
    items: [
      '<strong>Konzeption, Leitung und pädagogische Struktur:</strong> Guilherme de Góis Machado.',
      'Die Inhalte wurden mit KI-Unterstützung (Claude von Anthropic) unter Leitung des Autors verfasst.',
      'Jede Karte nennt die Quellen, auf die sie sich stützt; die meisten enthalten einen direkten Link zum Original.',
      'Die Übersetzungen wurden mit KI erstellt.',
      '<strong>Warum offenlegen?</strong> Aus Konsequenz mit den Ethik- und DSGVO-Hinweisen des Handbuchs selbst: Transparenz über den KI-Einsatz ist genau das, was Farol Lehrkräften empfiehlt.',
      'Farol ist ein Informationsangebot, keine klinische Anleitung: Identifikation und Diagnose gehören in die Hände qualifizierter Fachleute.',
    ],
    etica: 'Siehe auch',
  },
  nl: {
    title: 'Hoe het is gemaakt',
    cat: 'Transparantie',
    subtitle: 'Menselijke leiding en AI-assistentie — wie deed wat.',
    desc: 'Transparantie over het ontstaan van Farol: menselijke leiding en AI-assistentie.',
    items: [
      '<strong>Conceptie, leiding en pedagogische structuur:</strong> Guilherme de Góis Machado.',
      'De inhoud is opgesteld met AI-assistentie (Claude, van Anthropic) onder leiding van de auteur.',
      'Elke kaart vermeldt de bronnen waarop ze steunt; de meeste bevatten een directe link naar het origineel.',
      'De vertalingen zijn met AI gegenereerd.',
      '<strong>Waarom dit vermelden?</strong> Uit consistentie met de eigen Ethiek & AVG-richtlijnen van het handboek: transparantie over AI-gebruik is precies wat Farol leraren aanraadt.',
      'Farol is een informatieve bron, geen klinische leidraad: identificatie en diagnose horen bij gekwalificeerde professionals.',
    ],
    etica: 'Zie ook',
  },
  pl: {
    title: 'Jak powstał',
    cat: 'Przejrzystość',
    subtitle: 'Ludzkie kierownictwo i wsparcie AI — kto co zrobił.',
    desc: 'Przejrzystość procesu powstawania Farola: ludzkie kierownictwo i wsparcie AI.',
    items: [
      '<strong>Koncepcja, kierownictwo i struktura pedagogiczna:</strong> Guilherme de Góis Machado.',
      'Treści zostały opracowane ze wsparciem AI (Claude firmy Anthropic) pod kierunkiem autora.',
      'Każda karta podaje źródła, na których się opiera; większość zawiera bezpośredni link do oryginału.',
      'Tłumaczenia wygenerowano z użyciem AI.',
      '<strong>Po co to ujawniać?</strong> Dla spójności z wytycznymi Etyki i RODO samego podręcznika: przejrzystość w kwestii użycia AI to dokładnie to, co Farol zaleca nauczycielom.',
      'Farol to zasób informacyjny, nie wytyczne kliniczne: identyfikacja i diagnoza należą do wykwalifikowanych specjalistów.',
    ],
    etica: 'Zobacz też',
  },
  ro: {
    title: 'Cum a fost realizat',
    cat: 'Transparență',
    subtitle: 'Direcție umană și asistență AI — cine a făcut ce.',
    desc: 'Transparență privind realizarea Farol: direcție umană și asistență AI.',
    items: [
      '<strong>Concepție, direcție și structură pedagogică:</strong> Guilherme de Góis Machado.',
      'Conținutul a fost redactat cu asistență AI (Claude, de la Anthropic) sub direcția autorului.',
      'Fiecare fișă indică sursele pe care se bazează; majoritatea includ un link direct către original.',
      'Traducerile au fost generate cu AI.',
      '<strong>De ce dezvăluim?</strong> Din coerență cu îndrumările de Etică și GDPR ale manualului însuși: transparența privind utilizarea AI este exact ceea ce Farol le recomandă profesorilor.',
      'Farol este o resursă informativă, nu îndrumare clinică: identificarea și diagnosticul aparțin profesioniștilor calificați.',
    ],
    etica: 'Vezi și',
  },
  cs: {
    title: 'Jak vznikl',
    cat: 'Transparentnost',
    subtitle: 'Lidské vedení a asistence AI — kdo co dělal.',
    desc: 'Transparentnost o vzniku Farolu: lidské vedení a asistence AI.',
    items: [
      '<strong>Koncepce, vedení a pedagogická struktura:</strong> Guilherme de Góis Machado.',
      'Obsah byl vytvořen s asistencí AI (Claude od společnosti Anthropic) pod vedením autora.',
      'Každá karta uvádí zdroje, z nichž vychází; většina obsahuje přímý odkaz na originál.',
      'Překlady byly vygenerovány pomocí AI.',
      '<strong>Proč to zveřejňovat?</strong> Kvůli souladu s pokyny Etiky a GDPR samotné příručky: transparentnost ohledně použití AI je přesně to, co Farol učitelům doporučuje.',
      'Farol je informační zdroj, nikoli klinické vodítko: identifikace a diagnóza patří kvalifikovaným odborníkům.',
    ],
    etica: 'Viz také',
  },
  sv: {
    title: 'Hur den skapades',
    cat: 'Transparens',
    subtitle: 'Mänsklig ledning och AI-assistans — vem gjorde vad.',
    desc: 'Transparens om hur Farol skapades: mänsklig ledning och AI-assistans.',
    items: [
      '<strong>Idé, ledning och pedagogisk struktur:</strong> Guilherme de Góis Machado.',
      'Innehållet togs fram med AI-assistans (Claude, från Anthropic) under författarens ledning.',
      'Varje kort anger de källor det bygger på; de flesta har en direktlänk till originalet.',
      'Översättningarna genererades med AI.',
      '<strong>Varför berätta?</strong> För konsekvens med handbokens egna riktlinjer för etik och GDPR: transparens kring AI-användning är precis vad Farol rekommenderar lärare.',
      'Farol är en informationsresurs, inte klinisk vägledning: identifiering och diagnos hör till kvalificerade yrkespersoner.',
    ],
    etica: 'Se även',
  },
  da: {
    title: 'Sådan blev den til',
    cat: 'Gennemsigtighed',
    subtitle: 'Menneskelig ledelse og AI-assistance — hvem gjorde hvad.',
    desc: 'Gennemsigtighed om tilblivelsen af Farol: menneskelig ledelse og AI-assistance.',
    items: [
      '<strong>Idé, ledelse og pædagogisk struktur:</strong> Guilherme de Góis Machado.',
      'Indholdet blev udarbejdet med AI-assistance (Claude, fra Anthropic) under forfatterens ledelse.',
      'Hvert kort angiver de kilder, det bygger på; de fleste har et direkte link til originalen.',
      'Oversættelserne blev genereret med AI.',
      '<strong>Hvorfor oplyse det?</strong> Af konsekvens med håndbogens egne retningslinjer for etik og GDPR: gennemsigtighed om AI-brug er præcis, hvad Farol anbefaler lærere.',
      'Farol er en informationsressource, ikke klinisk vejledning: identifikation og diagnose hører til kvalificerede fagfolk.',
    ],
    etica: 'Se også',
  },
  fi: {
    title: 'Miten se tehtiin',
    cat: 'Läpinäkyvyys',
    subtitle: 'Ihmisen ohjaus ja tekoälyavusteisuus — kuka teki mitä.',
    desc: 'Läpinäkyvyyttä Farolin synnystä: ihmisen ohjaus ja tekoälyavusteisuus.',
    items: [
      '<strong>Konsepti, ohjaus ja pedagoginen rakenne:</strong> Guilherme de Góis Machado.',
      'Sisältö laadittiin tekoälyavusteisesti (Claude, Anthropic) tekijän ohjauksessa.',
      'Jokainen kortti ilmoittaa lähteet, joihin se nojaa; useimmissa on suora linkki alkuperäiseen.',
      'Käännökset tuotettiin tekoälyllä.',
      '<strong>Miksi kertoa tästä?</strong> Johdonmukaisuudesta käsikirjan omien etiikka- ja GDPR-ohjeiden kanssa: läpinäkyvyys tekoälyn käytöstä on juuri sitä, mitä Farol suosittelee opettajille.',
      'Farol on tiedollinen resurssi, ei kliininen ohje: tunnistaminen ja diagnosointi kuuluvat päteville ammattilaisille.',
    ],
    etica: 'Katso myös',
  },
  sk: {
    title: 'Ako vznikol',
    cat: 'Transparentnosť',
    subtitle: 'Ľudské vedenie a asistencia AI — kto čo robil.',
    desc: 'Transparentnosť o vzniku Farolu: ľudské vedenie a asistencia AI.',
    items: [
      '<strong>Koncepcia, vedenie a pedagogická štruktúra:</strong> Guilherme de Góis Machado.',
      'Obsah vznikol s asistenciou AI (Claude od spoločnosti Anthropic) pod vedením autora.',
      'Každá karta uvádza zdroje, z ktorých vychádza; väčšina obsahuje priamy odkaz na originál.',
      'Preklady boli vygenerované pomocou AI.',
      '<strong>Prečo to zverejniť?</strong> Pre súlad s pokynmi Etiky a GDPR samotnej príručky: transparentnosť ohľadom použitia AI je presne to, čo Farol učiteľom odporúča.',
      'Farol je informačný zdroj, nie klinické usmernenie: identifikácia a diagnóza patria kvalifikovaným odborníkom.',
    ],
    etica: 'Pozri tiež',
  },
  el: {
    title: 'Πώς φτιάχτηκε',
    cat: 'Διαφάνεια',
    subtitle: 'Ανθρώπινη διεύθυνση και βοήθεια ΤΝ — ποιος έκανε τι.',
    desc: 'Διαφάνεια για τη δημιουργία του Farol: ανθρώπινη διεύθυνση και βοήθεια ΤΝ.',
    items: [
      '<strong>Σύλληψη, διεύθυνση και παιδαγωγική δομή:</strong> Guilherme de Góis Machado.',
      'Το περιεχόμενο συντάχθηκε με βοήθεια ΤΝ (Claude, της Anthropic) υπό τη διεύθυνση του συγγραφέα.',
      'Κάθε κάρτα αναφέρει τις πηγές στις οποίες στηρίζεται· οι περισσότερες περιλαμβάνουν απευθείας σύνδεσμο προς το πρωτότυπο.',
      'Οι μεταφράσεις δημιουργήθηκαν με ΤΝ.',
      '<strong>Γιατί να το γνωστοποιήσουμε;</strong> Για συνέπεια με τις ίδιες τις οδηγίες Ηθικής & GDPR του εγχειριδίου: η διαφάνεια για τη χρήση ΤΝ είναι ακριβώς αυτό που το Farol συστήνει στους εκπαιδευτικούς.',
      'Το Farol είναι ενημερωτικός πόρος, όχι κλινική καθοδήγηση: η αναγνώριση και η διάγνωση ανήκουν σε εξειδικευμένους επαγγελματίες.',
    ],
    etica: 'Δείτε επίσης',
  },
  hu: {
    title: 'Hogyan készült',
    cat: 'Átláthatóság',
    subtitle: 'Emberi irányítás és MI-segítség — ki mit csinált.',
    desc: 'Átláthatóság a Farol készítéséről: emberi irányítás és MI-segítség.',
    items: [
      '<strong>Koncepció, irányítás és pedagógiai szerkezet:</strong> Guilherme de Góis Machado.',
      'A tartalom MI-segítséggel készült (Claude, az Anthropic modellje) a szerző irányításával.',
      'Minden kártya megadja a forrásokat, amelyekre támaszkodik; a legtöbbnél közvetlen link vezet az eredetihez.',
      'A fordítások MI-vel készültek.',
      '<strong>Miért közöljük?</strong> Összhangban a kézikönyv saját etikai és GDPR-útmutatásával: az MI-használat átláthatósága pontosan az, amit a Farol a tanároknak ajánl.',
      'A Farol tájékoztató jellegű forrás, nem klinikai útmutató: az azonosítás és a diagnózis képzett szakemberek feladata.',
    ],
    etica: 'Lásd még',
  },
  bg: {
    title: 'Как беше създаден',
    cat: 'Прозрачност',
    subtitle: 'Човешко ръководство и помощ от ИИ — кой какво е правил.',
    desc: 'Прозрачност за създаването на Farol: човешко ръководство и помощ от ИИ.',
    items: [
      '<strong>Концепция, ръководство и педагогическа структура:</strong> Guilherme de Góis Machado.',
      'Съдържанието е изготвено с помощта на ИИ (Claude на Anthropic) под ръководството на автора.',
      'Всяка карта посочва източниците, на които се опира; повечето включват пряка връзка към оригинала.',
      'Преводите са генерирани с ИИ.',
      '<strong>Защо го оповестяваме?</strong> За съгласуваност със собствените насоки на наръчника за етика и ОРЗД: прозрачността относно използването на ИИ е точно това, което Farol препоръчва на учителите.',
      'Farol е информационен ресурс, а не клинично ръководство: идентификацията и диагнозата принадлежат на квалифицирани специалисти.',
    ],
    etica: 'Вижте също',
  },
  lt: {
    title: 'Kaip jis sukurtas',
    cat: 'Skaidrumas',
    subtitle: 'Žmogaus vadovavimas ir DI pagalba — kas ką darė.',
    desc: 'Skaidrumas apie „Farol“ kūrimą: žmogaus vadovavimas ir DI pagalba.',
    items: [
      '<strong>Koncepcija, vadovavimas ir pedagoginė struktūra:</strong> Guilherme de Góis Machado.',
      'Turinys parengtas padedant DI (Anthropic „Claude“) autoriaus vadovaujamas.',
      'Kiekviena kortelė nurodo šaltinius, kuriais remiasi; daugumoje yra tiesioginė nuoroda į originalą.',
      'Vertimai sugeneruoti DI.',
      '<strong>Kodėl tai skelbiame?</strong> Dėl nuoseklumo su paties vadovo Etikos ir BDAR gairėmis: skaidrumas dėl DI naudojimo yra būtent tai, ką „Farol“ rekomenduoja mokytojams.',
      '„Farol“ — informacinis šaltinis, o ne klinikinės gairės: atpažinimas ir diagnozė priklauso kvalifikuotiems specialistams.',
    ],
    etica: 'Taip pat žr.',
  },
  lv: {
    title: 'Kā tas tapa',
    cat: 'Caurskatāmība',
    subtitle: 'Cilvēka vadība un MI palīdzība — kurš ko darīja.',
    desc: 'Caurskatāmība par Farol tapšanu: cilvēka vadība un MI palīdzība.',
    items: [
      '<strong>Koncepcija, vadība un pedagoģiskā struktūra:</strong> Guilherme de Góis Machado.',
      'Saturs tapis ar MI palīdzību (Anthropic „Claude“) autora vadībā.',
      'Katra kartīte norāda avotus, uz kuriem balstās; lielākajai daļai ir tieša saite uz oriģinālu.',
      'Tulkojumi ģenerēti ar MI.',
      '<strong>Kāpēc to atklāt?</strong> Saskaņā ar paša rokasgrāmatas Ētikas un VDAR norādēm: caurskatāmība par MI lietošanu ir tieši tas, ko Farol iesaka skolotājiem.',
      'Farol ir informatīvs resurss, nevis klīniskas vadlīnijas: identificēšana un diagnostika pieder kvalificētiem speciālistiem.',
    ],
    etica: 'Skatīt arī',
  },
  et: {
    title: 'Kuidas see valmis',
    cat: 'Läbipaistvus',
    subtitle: 'Inimese juhtimine ja tehisaru abi — kes mida tegi.',
    desc: 'Läbipaistvus Faroli valmimisest: inimese juhtimine ja tehisaru abi.',
    items: [
      '<strong>Kontseptsioon, juhtimine ja pedagoogiline ülesehitus:</strong> Guilherme de Góis Machado.',
      'Sisu koostati tehisaru abiga (Anthropicu Claude) autori juhtimisel.',
      'Iga kaart nimetab allikad, millele see tugineb; enamikul on otselink originaalile.',
      'Tõlked genereeriti tehisaruga.',
      '<strong>Miks sellest rääkida?</strong> Kooskõlas käsiraamatu enda eetika- ja isikuandmete kaitse suunistega: läbipaistvus tehisaru kasutamise kohta ongi just see, mida Farol õpetajatele soovitab.',
      'Farol on teabeallikas, mitte kliiniline juhis: tuvastamine ja diagnoosimine kuuluvad kvalifitseeritud spetsialistidele.',
    ],
    etica: 'Vaata ka',
  },
  sl: {
    title: 'Kako je nastal',
    cat: 'Preglednost',
    subtitle: 'Človeško vodenje in pomoč UI — kdo je kaj naredil.',
    desc: 'Preglednost o nastanku Farola: človeško vodenje in pomoč UI.',
    items: [
      '<strong>Zasnova, vodenje in pedagoška struktura:</strong> Guilherme de Góis Machado.',
      'Vsebina je nastala s pomočjo UI (Claude podjetja Anthropic) pod avtorjevim vodstvom.',
      'Vsaka kartica navaja vire, na katere se opira; večina vsebuje neposredno povezavo do izvirnika.',
      'Prevodi so bili ustvarjeni z UI.',
      '<strong>Zakaj to razkriti?</strong> Zaradi skladnosti s smernicami Etike in GDPR samega priročnika: preglednost glede uporabe UI je prav to, kar Farol priporoča učiteljem.',
      'Farol je informativni vir, ne klinična navodila: prepoznavanje in diagnoza pripadata usposobljenim strokovnjakom.',
    ],
    etica: 'Glej tudi',
  },
  ga: {
    title: 'Conas a rinneadh é',
    cat: 'Trédhearcacht',
    subtitle: 'Stiúradh daonna agus cúnamh IS — cé a rinne céard.',
    desc: 'Trédhearcacht faoi chruthú Farol: stiúradh daonna agus cúnamh IS.',
    items: [
      '<strong>Coincheap, stiúradh agus struchtúr oideolaíoch:</strong> Guilherme de Góis Machado.',
      'Dréachtaíodh an t-ábhar le cúnamh IS (Claude, de chuid Anthropic) faoi stiúir an údair.',
      'Liostaíonn gach cárta na foinsí a mbaineann sé leas astu; tá nasc díreach chuig an mbunfhoinse ag a bhformhór.',
      'Gineadh na haistriúcháin le IS.',
      '<strong>Cén fáth é seo a nochtadh?</strong> Ar mhaithe le comhsheasmhacht le treoir Eitice agus RGCS an lámhleabhair féin: is í an trédhearcacht faoi úsáid IS go díreach a mholann Farol do mhúinteoirí.',
      'Acmhainn faisnéise é Farol, ní treoir chliniciúil: baineann sainaithint agus diagnóis le gairmithe cáilithe.',
    ],
    etica: 'Féach freisin',
  },
  mt: {
    title: 'Kif sar',
    cat: 'Trasparenza',
    subtitle: 'Direzzjoni umana u għajnuna tal-IA — min għamel xiex.',
    desc: 'Trasparenza dwar kif sar Farol: direzzjoni umana u għajnuna tal-IA.',
    items: [
      '<strong>Konċezzjoni, direzzjoni u struttura pedagoġika:</strong> Guilherme de Góis Machado.',
      'Il-kontenut tfassal bl-għajnuna tal-IA (Claude, ta’ Anthropic) taħt id-direzzjoni tal-awtur.',
      'Kull karta telenka s-sorsi li tibbaża fuqhom; il-biċċa l-kbira jinkludu link dirett għall-oriġinal.',
      'It-traduzzjonijiet ġew iġġenerati bl-IA.',
      '<strong>Għaliex niddikjarawh?</strong> Għal koerenza mal-gwida tal-Etika u l-GDPR tal-manwal stess: it-trasparenza dwar l-użu tal-IA hija eżattament dak li Farol jirrakkomanda lill-għalliema.',
      'Farol huwa riżors informattiv, mhux gwida klinika: l-identifikazzjoni u d-dijanjożi jappartjenu lil professjonisti kkwalifikati.',
    ],
    etica: 'Ara wkoll',
  },
  tr: {
    title: 'Nasıl yapıldı',
    cat: 'Şeffaflık',
    subtitle: 'İnsan yönetimi ve yapay zekâ desteği — kim ne yaptı.',
    desc: 'Farol’un nasıl oluşturulduğuna dair şeffaflık: insan yönetimi ve yapay zekâ desteği.',
    items: [
      '<strong>Tasarım, yönetim ve pedagojik yapı:</strong> Guilherme de Góis Machado.',
      'İçerik, yazarın yönetiminde yapay zekâ desteğiyle (Anthropic’in Claude modeli) kaleme alındı.',
      'Her kart dayandığı kaynakları listeler; çoğu doğrudan özgün metne bağlantı verir.',
      'Çeviriler yapay zekâ ile üretildi.',
      '<strong>Neden açıklıyoruz?</strong> El kitabının kendi Etik ve KVKK yönlendirmesiyle tutarlı olmak için: yapay zekâ kullanımında şeffaflık, Farol’un öğretmenlere tam olarak önerdiği şeydir.',
      'Farol bilgilendirici bir kaynaktır, klinik bir rehber değildir: tanılama ve tanı nitelikli uzmanların işidir.',
    ],
    etica: 'Ayrıca bakınız',
  },
  no: {
    title: 'Slik ble den til',
    cat: 'Åpenhet',
    subtitle: 'Menneskelig ledelse og KI-assistanse — hvem gjorde hva.',
    desc: 'Åpenhet om hvordan Farol ble til: menneskelig ledelse og KI-assistanse.',
    items: [
      '<strong>Idé, ledelse og pedagogisk struktur:</strong> Guilherme de Góis Machado.',
      'Innholdet ble skrevet med KI-assistanse (Claude, fra Anthropic) under forfatterens ledelse.',
      'Hvert kort oppgir kildene det bygger på; de fleste lenker direkte til originalen.',
      'Oversettelsene ble laget med KI.',
      '<strong>Hvorfor si det?</strong> For å være konsekvent med håndbokens egne råd om etikk og personvern: åpenhet om bruk av KI er nettopp det Farol anbefaler lærere.',
      'Farol er en informasjonsressurs, ikke klinisk veiledning: identifisering og diagnostisering hører til kvalifisert fagpersonell.',
    ],
    etica: 'Se også',
  },
};

// hreflang / footer hrefs for the transparency page (PT slug at root, shared
// English slug under each language prefix — same convention as sobre/about).
export function allMadeHrefs(base: string): Record<Lang, string> {
  const out = {} as Record<Lang, string>;
  const langs: Lang[] = ALL_LANGS;
  for (const l of langs) out[l] = l === 'pt' ? `${base}como-foi-feito/` : `${base}${l}/how-it-was-made/`;
  return out;
}
