// "Como foi feito" — transparency page about how Farol was created.
// Discloses the human direction / AI assistance split, verification steps,
// and the informational (non-clinical) scope, consistent with the manual's
// own Ética & RGPD guidance. One entry per language.
import type { Lang } from './i18n';

export interface MadePage {
  title: string;      // page + footer link title
  cat: string;        // card category stamp
  subtitle: string;
  desc: string;       // meta description
  items: string[];    // six disclosure bullets (HTML allowed)
  etica: string;      // label prefix for the Ética & RGPD link row
}

export const made: Record<Lang, MadePage> = {
  pt: {
    title: 'Como foi feito',
    cat: 'Transparência',
    subtitle: 'Direção humana, assistência de IA, verificação e revisão — quem fez o quê.',
    desc: 'Transparência sobre o processo de criação do Farol: direção humana, assistência de IA, verificação das fontes e revisão.',
    items: [
      '<strong>Conceção, direção e estrutura pedagógica:</strong> Guilherme de Góis Machado.',
      'O conteúdo foi redigido com assistência de IA (Claude, da Anthropic) sob direção do autor, com revisão humana de todas as fichas.',
      'As referências académicas foram verificadas contra as fontes citadas — cada entrada inclui a respetiva ligação DOI.',
      'As traduções foram geradas com IA e passaram por três rondas de revisão.',
      '<strong>Porquê divulgar?</strong> Por coerência com a orientação de Ética & RGPD do próprio manual: a transparência sobre o uso de IA é precisamente o que o Farol recomenda aos docentes.',
      'O Farol é um recurso informativo, não orientação clínica: a identificação e o diagnóstico cabem a profissionais qualificados.',
    ],
    etica: 'Ver também',
  },
  en: {
    title: 'How it was made',
    cat: 'Transparency',
    subtitle: 'Human direction, AI assistance, verification and review — who did what.',
    desc: 'Transparency about how Farol was created: human direction, AI assistance, source verification and review.',
    items: [
      '<strong>Conception, direction and pedagogical structure:</strong> Guilherme de Góis Machado.',
      'The content was drafted with AI assistance (Claude, by Anthropic) under the author’s direction, with human review of every card.',
      'Academic references were checked against the cited sources — each entry includes its DOI link.',
      'Translations were AI-generated and went through three proofreading passes.',
      '<strong>Why disclose?</strong> For consistency with the manual’s own Ethics & GDPR guidance: transparency about AI use is precisely what Farol recommends to teachers.',
      'Farol is an informational resource, not clinical guidance: identification and diagnosis belong to qualified professionals.',
    ],
    etica: 'See also',
  },
  es: {
    title: 'Cómo se hizo',
    cat: 'Transparencia',
    subtitle: 'Dirección humana, asistencia de IA, verificación y revisión: quién hizo qué.',
    desc: 'Transparencia sobre el proceso de creación de Farol: dirección humana, asistencia de IA, verificación de fuentes y revisión.',
    items: [
      '<strong>Concepción, dirección y estructura pedagógica:</strong> Guilherme de Góis Machado.',
      'El contenido se redactó con asistencia de IA (Claude, de Anthropic) bajo la dirección del autor, con revisión humana de todas las fichas.',
      'Las referencias académicas se verificaron contra las fuentes citadas: cada entrada incluye su enlace DOI.',
      'Las traducciones se generaron con IA y pasaron por tres rondas de revisión.',
      '<strong>¿Por qué divulgarlo?</strong> Por coherencia con la propia guía de Ética y RGPD del manual: la transparencia sobre el uso de la IA es precisamente lo que Farol recomienda al profesorado.',
      'Farol es un recurso informativo, no una orientación clínica: la identificación y el diagnóstico corresponden a profesionales cualificados.',
    ],
    etica: 'Ver también',
  },
  fr: {
    title: 'Comment il a été fait',
    cat: 'Transparence',
    subtitle: 'Direction humaine, assistance de l’IA, vérification et relecture — qui a fait quoi.',
    desc: 'Transparence sur la création de Farol : direction humaine, assistance de l’IA, vérification des sources et relecture.',
    items: [
      '<strong>Conception, direction et structure pédagogique :</strong> Guilherme de Góis Machado.',
      'Le contenu a été rédigé avec l’assistance d’une IA (Claude, d’Anthropic) sous la direction de l’auteur, avec une relecture humaine de chaque fiche.',
      'Les références académiques ont été vérifiées auprès des sources citées — chaque entrée comporte son lien DOI.',
      'Les traductions ont été générées par IA et ont fait l’objet de trois relectures.',
      '<strong>Pourquoi le dire ?</strong> Par cohérence avec les repères Éthique & RGPD du manuel lui-même : la transparence sur l’usage de l’IA est précisément ce que Farol recommande aux enseignants.',
      'Farol est une ressource d’information, pas un guide clinique : l’identification et le diagnostic relèvent de professionnels qualifiés.',
    ],
    etica: 'Voir aussi',
  },
  it: {
    title: 'Come è stato fatto',
    cat: 'Trasparenza',
    subtitle: 'Direzione umana, assistenza dell’IA, verifica e revisione — chi ha fatto cosa.',
    desc: 'Trasparenza sul processo di creazione di Farol: direzione umana, assistenza dell’IA, verifica delle fonti e revisione.',
    items: [
      '<strong>Concezione, direzione e struttura pedagogica:</strong> Guilherme de Góis Machado.',
      'I contenuti sono stati redatti con l’assistenza di un’IA (Claude, di Anthropic) sotto la direzione dell’autore, con revisione umana di ogni scheda.',
      'I riferimenti accademici sono stati verificati sulle fonti citate — ogni voce include il relativo link DOI.',
      'Le traduzioni sono state generate con l’IA e sottoposte a tre cicli di revisione.',
      '<strong>Perché dichiararlo?</strong> Per coerenza con le indicazioni di Etica & GDPR del manuale stesso: la trasparenza sull’uso dell’IA è esattamente ciò che Farol raccomanda ai docenti.',
      'Farol è una risorsa informativa, non una guida clinica: identificazione e diagnosi spettano a professionisti qualificati.',
    ],
    etica: 'Vedi anche',
  },
  hr: {
    title: 'Kako je nastao',
    cat: 'Transparentnost',
    subtitle: 'Ljudsko vodstvo, pomoć umjetne inteligencije, provjera i lektura — tko je što radio.',
    desc: 'Transparentnost o nastanku Farola: ljudsko vodstvo, pomoć umjetne inteligencije, provjera izvora i lektura.',
    items: [
      '<strong>Koncepcija, vodstvo i pedagoška struktura:</strong> Guilherme de Góis Machado.',
      'Sadržaj je izrađen uz pomoć umjetne inteligencije (Claude, tvrtke Anthropic) pod vodstvom autora, uz ljudsku provjeru svake kartice.',
      'Akademske reference provjerene su prema citiranim izvorima — svaki unos sadrži pripadajuću DOI poveznicu.',
      'Prijevodi su generirani umjetnom inteligencijom i prošli su tri kruga lekture.',
      '<strong>Zašto to objaviti?</strong> Radi dosljednosti sa smjernicama Etike i GDPR-a samog priručnika: transparentnost o korištenju UI upravo je ono što Farol preporučuje nastavnicima.',
      'Farol je informativni resurs, a ne kliničke smjernice: identifikacija i dijagnoza pripadaju kvalificiranim stručnjacima.',
    ],
    etica: 'Vidi također',
  },
  de: {
    title: 'Wie es entstanden ist',
    cat: 'Transparenz',
    subtitle: 'Menschliche Leitung, KI-Unterstützung, Prüfung und Korrektur — wer was gemacht hat.',
    desc: 'Transparenz über die Entstehung von Farol: menschliche Leitung, KI-Unterstützung, Quellenprüfung und Korrektur.',
    items: [
      '<strong>Konzeption, Leitung und pädagogische Struktur:</strong> Guilherme de Góis Machado.',
      'Die Inhalte wurden mit KI-Unterstützung (Claude von Anthropic) unter Leitung des Autors verfasst, mit menschlicher Prüfung jeder Karte.',
      'Die akademischen Referenzen wurden an den zitierten Quellen geprüft — jeder Eintrag enthält den zugehörigen DOI-Link.',
      'Die Übersetzungen wurden mit KI erstellt und durchliefen drei Korrekturrunden.',
      '<strong>Warum offenlegen?</strong> Aus Konsequenz mit den Ethik- und DSGVO-Hinweisen des Handbuchs selbst: Transparenz über den KI-Einsatz ist genau das, was Farol Lehrkräften empfiehlt.',
      'Farol ist ein Informationsangebot, keine klinische Anleitung: Identifikation und Diagnose gehören in die Hände qualifizierter Fachleute.',
    ],
    etica: 'Siehe auch',
  },
  nl: {
    title: 'Hoe het is gemaakt',
    cat: 'Transparantie',
    subtitle: 'Menselijke leiding, AI-assistentie, verificatie en revisie — wie deed wat.',
    desc: 'Transparantie over het ontstaan van Farol: menselijke leiding, AI-assistentie, bronverificatie en revisie.',
    items: [
      '<strong>Conceptie, leiding en pedagogische structuur:</strong> Guilherme de Góis Machado.',
      'De inhoud is opgesteld met AI-assistentie (Claude, van Anthropic) onder leiding van de auteur, met menselijke controle van elke kaart.',
      'De academische referenties zijn gecontroleerd aan de hand van de geciteerde bronnen — elke vermelding bevat de bijbehorende DOI-link.',
      'De vertalingen zijn met AI gegenereerd en hebben drie revisierondes doorlopen.',
      '<strong>Waarom dit vermelden?</strong> Uit consistentie met de eigen Ethiek & AVG-richtlijnen van het handboek: transparantie over AI-gebruik is precies wat Farol leraren aanraadt.',
      'Farol is een informatieve bron, geen klinische leidraad: identificatie en diagnose horen bij gekwalificeerde professionals.',
    ],
    etica: 'Zie ook',
  },
  pl: {
    title: 'Jak powstał',
    cat: 'Przejrzystość',
    subtitle: 'Ludzkie kierownictwo, wsparcie AI, weryfikacja i korekta — kto co zrobił.',
    desc: 'Przejrzystość procesu powstawania Farola: ludzkie kierownictwo, wsparcie AI, weryfikacja źródeł i korekta.',
    items: [
      '<strong>Koncepcja, kierownictwo i struktura pedagogiczna:</strong> Guilherme de Góis Machado.',
      'Treści zostały opracowane ze wsparciem AI (Claude firmy Anthropic) pod kierunkiem autora, z ludzką weryfikacją każdej karty.',
      'Odniesienia akademickie zweryfikowano względem cytowanych źródeł — każda pozycja zawiera link DOI.',
      'Tłumaczenia wygenerowano z użyciem AI i przeszły trzy rundy korekty.',
      '<strong>Po co to ujawniać?</strong> Dla spójności z wytycznymi Etyki i RODO samego podręcznika: przejrzystość w kwestii użycia AI to dokładnie to, co Farol zaleca nauczycielom.',
      'Farol to zasób informacyjny, nie wytyczne kliniczne: identyfikacja i diagnoza należą do wykwalifikowanych specjalistów.',
    ],
    etica: 'Zobacz też',
  },
  ro: {
    title: 'Cum a fost realizat',
    cat: 'Transparență',
    subtitle: 'Direcție umană, asistență AI, verificare și revizuire — cine a făcut ce.',
    desc: 'Transparență privind realizarea Farol: direcție umană, asistență AI, verificarea surselor și revizuire.',
    items: [
      '<strong>Concepție, direcție și structură pedagogică:</strong> Guilherme de Góis Machado.',
      'Conținutul a fost redactat cu asistență AI (Claude, de la Anthropic) sub direcția autorului, cu revizuire umană a fiecărei fișe.',
      'Referințele academice au fost verificate în raport cu sursele citate — fiecare intrare include linkul DOI aferent.',
      'Traducerile au fost generate cu AI și au trecut prin trei runde de revizuire.',
      '<strong>De ce dezvăluim?</strong> Din coerență cu îndrumările de Etică și GDPR ale manualului însuși: transparența privind utilizarea AI este exact ceea ce Farol le recomandă profesorilor.',
      'Farol este o resursă informativă, nu îndrumare clinică: identificarea și diagnosticul aparțin profesioniștilor calificați.',
    ],
    etica: 'Vezi și',
  },
  cs: {
    title: 'Jak vznikl',
    cat: 'Transparentnost',
    subtitle: 'Lidské vedení, asistence AI, ověřování a korektury — kdo co dělal.',
    desc: 'Transparentnost o vzniku Farolu: lidské vedení, asistence AI, ověření zdrojů a korektury.',
    items: [
      '<strong>Koncepce, vedení a pedagogická struktura:</strong> Guilherme de Góis Machado.',
      'Obsah byl vytvořen s asistencí AI (Claude od společnosti Anthropic) pod vedením autora, s lidskou kontrolou každé karty.',
      'Akademické reference byly ověřeny podle citovaných zdrojů — každá položka obsahuje příslušný odkaz DOI.',
      'Překlady byly vygenerovány pomocí AI a prošly třemi koly korektur.',
      '<strong>Proč to zveřejňovat?</strong> Kvůli souladu s pokyny Etiky a GDPR samotné příručky: transparentnost ohledně použití AI je přesně to, co Farol učitelům doporučuje.',
      'Farol je informační zdroj, nikoli klinické vodítko: identifikace a diagnóza patří kvalifikovaným odborníkům.',
    ],
    etica: 'Viz také',
  },
  sv: {
    title: 'Hur den skapades',
    cat: 'Transparens',
    subtitle: 'Mänsklig ledning, AI-assistans, verifiering och granskning — vem gjorde vad.',
    desc: 'Transparens om hur Farol skapades: mänsklig ledning, AI-assistans, källverifiering och granskning.',
    items: [
      '<strong>Idé, ledning och pedagogisk struktur:</strong> Guilherme de Góis Machado.',
      'Innehållet togs fram med AI-assistans (Claude, från Anthropic) under författarens ledning, med mänsklig granskning av varje kort.',
      'De akademiska referenserna kontrollerades mot de citerade källorna — varje post har sin DOI-länk.',
      'Översättningarna genererades med AI och gick igenom tre granskningsomgångar.',
      '<strong>Varför berätta?</strong> För konsekvens med handbokens egna riktlinjer för etik och GDPR: transparens kring AI-användning är precis vad Farol rekommenderar lärare.',
      'Farol är en informationsresurs, inte klinisk vägledning: identifiering och diagnos hör till kvalificerade yrkespersoner.',
    ],
    etica: 'Se även',
  },
  da: {
    title: 'Sådan blev den til',
    cat: 'Gennemsigtighed',
    subtitle: 'Menneskelig ledelse, AI-assistance, verifikation og korrektur — hvem gjorde hvad.',
    desc: 'Gennemsigtighed om tilblivelsen af Farol: menneskelig ledelse, AI-assistance, kildeverifikation og korrektur.',
    items: [
      '<strong>Idé, ledelse og pædagogisk struktur:</strong> Guilherme de Góis Machado.',
      'Indholdet blev udarbejdet med AI-assistance (Claude, fra Anthropic) under forfatterens ledelse, med menneskelig gennemgang af hvert kort.',
      'De akademiske referencer blev kontrolleret mod de citerede kilder — hver post har sit DOI-link.',
      'Oversættelserne blev genereret med AI og gennemgik tre korrekturrunder.',
      '<strong>Hvorfor oplyse det?</strong> Af konsekvens med håndbogens egne retningslinjer for etik og GDPR: gennemsigtighed om AI-brug er præcis, hvad Farol anbefaler lærere.',
      'Farol er en informationsressource, ikke klinisk vejledning: identifikation og diagnose hører til kvalificerede fagfolk.',
    ],
    etica: 'Se også',
  },
  fi: {
    title: 'Miten se tehtiin',
    cat: 'Läpinäkyvyys',
    subtitle: 'Ihmisen ohjaus, tekoälyavusteisuus, varmennus ja oikoluku — kuka teki mitä.',
    desc: 'Läpinäkyvyyttä Farolin synnystä: ihmisen ohjaus, tekoälyavusteisuus, lähteiden varmennus ja oikoluku.',
    items: [
      '<strong>Konsepti, ohjaus ja pedagoginen rakenne:</strong> Guilherme de Góis Machado.',
      'Sisältö laadittiin tekoälyavusteisesti (Claude, Anthropic) tekijän ohjauksessa, ja ihminen tarkisti jokaisen kortin.',
      'Akateemiset lähdeviitteet tarkistettiin siteerattuja lähteitä vasten — jokaisessa on DOI-linkki.',
      'Käännökset tuotettiin tekoälyllä, ja ne kävivät läpi kolme oikolukukierrosta.',
      '<strong>Miksi kertoa tästä?</strong> Johdonmukaisuudesta käsikirjan omien etiikka- ja GDPR-ohjeiden kanssa: läpinäkyvyys tekoälyn käytöstä on juuri sitä, mitä Farol suosittelee opettajille.',
      'Farol on tiedollinen resurssi, ei kliininen ohje: tunnistaminen ja diagnosointi kuuluvat päteville ammattilaisille.',
    ],
    etica: 'Katso myös',
  },
  sk: {
    title: 'Ako vznikol',
    cat: 'Transparentnosť',
    subtitle: 'Ľudské vedenie, asistencia AI, overovanie a korektúry — kto čo robil.',
    desc: 'Transparentnosť o vzniku Farolu: ľudské vedenie, asistencia AI, overenie zdrojov a korektúry.',
    items: [
      '<strong>Koncepcia, vedenie a pedagogická štruktúra:</strong> Guilherme de Góis Machado.',
      'Obsah vznikol s asistenciou AI (Claude od spoločnosti Anthropic) pod vedením autora, s ľudskou kontrolou každej karty.',
      'Akademické referencie boli overené podľa citovaných zdrojov — každá položka obsahuje príslušný odkaz DOI.',
      'Preklady boli vygenerované pomocou AI a prešli tromi kolami korektúr.',
      '<strong>Prečo to zverejniť?</strong> Pre súlad s pokynmi Etiky a GDPR samotnej príručky: transparentnosť ohľadom použitia AI je presne to, čo Farol učiteľom odporúča.',
      'Farol je informačný zdroj, nie klinické usmernenie: identifikácia a diagnóza patria kvalifikovaným odborníkom.',
    ],
    etica: 'Pozri tiež',
  },
  el: {
    title: 'Πώς φτιάχτηκε',
    cat: 'Διαφάνεια',
    subtitle: 'Ανθρώπινη διεύθυνση, βοήθεια ΤΝ, επαλήθευση και επιμέλεια — ποιος έκανε τι.',
    desc: 'Διαφάνεια για τη δημιουργία του Farol: ανθρώπινη διεύθυνση, βοήθεια ΤΝ, επαλήθευση πηγών και επιμέλεια.',
    items: [
      '<strong>Σύλληψη, διεύθυνση και παιδαγωγική δομή:</strong> Guilherme de Góis Machado.',
      'Το περιεχόμενο συντάχθηκε με βοήθεια ΤΝ (Claude, της Anthropic) υπό τη διεύθυνση του συγγραφέα, με ανθρώπινο έλεγχο κάθε κάρτας.',
      'Οι ακαδημαϊκές αναφορές επαληθεύτηκαν με βάση τις παρατιθέμενες πηγές — κάθε καταχώριση περιλαμβάνει τον σύνδεσμο DOI της.',
      'Οι μεταφράσεις δημιουργήθηκαν με ΤΝ και πέρασαν από τρεις γύρους επιμέλειας.',
      '<strong>Γιατί να το γνωστοποιήσουμε;</strong> Για συνέπεια με τις ίδιες τις οδηγίες Ηθικής & GDPR του εγχειριδίου: η διαφάνεια για τη χρήση ΤΝ είναι ακριβώς αυτό που το Farol συστήνει στους εκπαιδευτικούς.',
      'Το Farol είναι ενημερωτικός πόρος, όχι κλινική καθοδήγηση: η αναγνώριση και η διάγνωση ανήκουν σε εξειδικευμένους επαγγελματίες.',
    ],
    etica: 'Δείτε επίσης',
  },
  hu: {
    title: 'Hogyan készült',
    cat: 'Átláthatóság',
    subtitle: 'Emberi irányítás, MI-segítség, ellenőrzés és lektorálás — ki mit csinált.',
    desc: 'Átláthatóság a Farol készítéséről: emberi irányítás, MI-segítség, forrásellenőrzés és lektorálás.',
    items: [
      '<strong>Koncepció, irányítás és pedagógiai szerkezet:</strong> Guilherme de Góis Machado.',
      'A tartalom MI-segítséggel készült (Claude, az Anthropic modellje) a szerző irányításával, minden kártya emberi ellenőrzésével.',
      'A tudományos hivatkozásokat az idézett forrásokkal vetettük össze — minden tétel tartalmazza a DOI-hivatkozását.',
      'A fordítások MI-vel készültek, és három lektorálási körön mentek át.',
      '<strong>Miért közöljük?</strong> Összhangban a kézikönyv saját etikai és GDPR-útmutatásával: az MI-használat átláthatósága pontosan az, amit a Farol a tanároknak ajánl.',
      'A Farol tájékoztató jellegű forrás, nem klinikai útmutató: az azonosítás és a diagnózis képzett szakemberek feladata.',
    ],
    etica: 'Lásd még',
  },
  bg: {
    title: 'Как беше създаден',
    cat: 'Прозрачност',
    subtitle: 'Човешко ръководство, помощ от ИИ, проверка и редакция — кой какво е правил.',
    desc: 'Прозрачност за създаването на Farol: човешко ръководство, помощ от ИИ, проверка на източниците и редакция.',
    items: [
      '<strong>Концепция, ръководство и педагогическа структура:</strong> Guilherme de Góis Machado.',
      'Съдържанието е изготвено с помощта на ИИ (Claude на Anthropic) под ръководството на автора, с човешка проверка на всяка карта.',
      'Академичните препратки са проверени спрямо цитираните източници — всяка включва своята DOI връзка.',
      'Преводите са генерирани с ИИ и са преминали през три кръга редакция.',
      '<strong>Защо го оповестяваме?</strong> За съгласуваност със собствените насоки на наръчника за етика и ОРЗД: прозрачността относно използването на ИИ е точно това, което Farol препоръчва на учителите.',
      'Farol е информационен ресурс, а не клинично ръководство: идентификацията и диагнозата принадлежат на квалифицирани специалисти.',
    ],
    etica: 'Вижте също',
  },
  lt: {
    title: 'Kaip jis sukurtas',
    cat: 'Skaidrumas',
    subtitle: 'Žmogaus vadovavimas, DI pagalba, tikrinimas ir redagavimas — kas ką darė.',
    desc: 'Skaidrumas apie „Farol“ kūrimą: žmogaus vadovavimas, DI pagalba, šaltinių tikrinimas ir redagavimas.',
    items: [
      '<strong>Koncepcija, vadovavimas ir pedagoginė struktūra:</strong> Guilherme de Góis Machado.',
      'Turinys parengtas padedant DI (Anthropic „Claude“) autoriaus vadovaujamas, kiekvieną kortelę peržiūrėjo žmogus.',
      'Akademinės nuorodos patikrintos pagal cituojamus šaltinius — kiekviena turi savo DOI nuorodą.',
      'Vertimai sugeneruoti DI ir praėjo tris redagavimo etapus.',
      '<strong>Kodėl tai skelbiame?</strong> Dėl nuoseklumo su paties vadovo Etikos ir BDAR gairėmis: skaidrumas dėl DI naudojimo yra būtent tai, ką „Farol“ rekomenduoja mokytojams.',
      '„Farol“ — informacinis šaltinis, o ne klinikinės gairės: atpažinimas ir diagnozė priklauso kvalifikuotiems specialistams.',
    ],
    etica: 'Taip pat žr.',
  },
  lv: {
    title: 'Kā tas tapa',
    cat: 'Caurskatāmība',
    subtitle: 'Cilvēka vadība, MI palīdzība, pārbaude un korektūra — kurš ko darīja.',
    desc: 'Caurskatāmība par Farol tapšanu: cilvēka vadība, MI palīdzība, avotu pārbaude un korektūra.',
    items: [
      '<strong>Koncepcija, vadība un pedagoģiskā struktūra:</strong> Guilherme de Góis Machado.',
      'Saturs tapis ar MI palīdzību (Anthropic „Claude“) autora vadībā, un katru karti pārbaudījis cilvēks.',
      'Akadēmiskās atsauces pārbaudītas pret citētajiem avotiem — katrai ir sava DOI saite.',
      'Tulkojumi ģenerēti ar MI un izgājuši trīs korektūras kārtas.',
      '<strong>Kāpēc to atklāt?</strong> Saskaņā ar paša rokasgrāmatas Ētikas un VDAR norādēm: caurskatāmība par MI lietošanu ir tieši tas, ko Farol iesaka skolotājiem.',
      'Farol ir informatīvs resurss, nevis klīniskas vadlīnijas: identificēšana un diagnostika pieder kvalificētiem speciālistiem.',
    ],
    etica: 'Skatīt arī',
  },
  et: {
    title: 'Kuidas see valmis',
    cat: 'Läbipaistvus',
    subtitle: 'Inimese juhtimine, tehisaru abi, kontroll ja toimetamine — kes mida tegi.',
    desc: 'Läbipaistvus Faroli valmimisest: inimese juhtimine, tehisaru abi, allikate kontroll ja toimetamine.',
    items: [
      '<strong>Kontseptsioon, juhtimine ja pedagoogiline ülesehitus:</strong> Guilherme de Góis Machado.',
      'Sisu koostati tehisaru abiga (Anthropicu Claude) autori juhtimisel, iga kaardi vaatas üle inimene.',
      'Akadeemilised viited kontrolliti tsiteeritud allikate põhjal — igal kirjel on oma DOI-link.',
      'Tõlked genereeriti tehisaruga ja läbisid kolm toimetamisringi.',
      '<strong>Miks sellest rääkida?</strong> Kooskõlas käsiraamatu enda eetika- ja isikuandmete kaitse suunistega: läbipaistvus tehisaru kasutamise kohta ongi just see, mida Farol õpetajatele soovitab.',
      'Farol on teabeallikas, mitte kliiniline juhis: tuvastamine ja diagnoosimine kuuluvad kvalifitseeritud spetsialistidele.',
    ],
    etica: 'Vaata ka',
  },
  sl: {
    title: 'Kako je nastal',
    cat: 'Preglednost',
    subtitle: 'Človeško vodenje, pomoč UI, preverjanje in lektura — kdo je kaj naredil.',
    desc: 'Preglednost o nastanku Farola: človeško vodenje, pomoč UI, preverjanje virov in lektura.',
    items: [
      '<strong>Zasnova, vodenje in pedagoška struktura:</strong> Guilherme de Góis Machado.',
      'Vsebina je nastala s pomočjo UI (Claude podjetja Anthropic) pod avtorjevim vodstvom, vsako kartico je pregledal človek.',
      'Akademske reference so preverjene po citiranih virih — vsak vnos vsebuje svojo povezavo DOI.',
      'Prevodi so bili ustvarjeni z UI in so šli skozi tri kroge lekture.',
      '<strong>Zakaj to razkriti?</strong> Zaradi skladnosti s smernicami Etike in GDPR samega priročnika: preglednost glede uporabe UI je prav to, kar Farol priporoča učiteljem.',
      'Farol je informativni vir, ne klinična navodila: prepoznavanje in diagnoza pripadata usposobljenim strokovnjakom.',
    ],
    etica: 'Glej tudi',
  },
  ga: {
    title: 'Conas a rinneadh é',
    cat: 'Trédhearcacht',
    subtitle: 'Stiúradh daonna, cúnamh IS, fíorú agus profléitheoireacht — cé a rinne céard.',
    desc: 'Trédhearcacht faoi chruthú Farol: stiúradh daonna, cúnamh IS, fíorú foinsí agus profléitheoireacht.',
    items: [
      '<strong>Coincheap, stiúradh agus struchtúr oideolaíoch:</strong> Guilherme de Góis Machado.',
      'Dréachtaíodh an t-ábhar le cúnamh IS (Claude, de chuid Anthropic) faoi stiúir an údair, agus rinne duine athbhreithniú ar gach cárta.',
      'Fíoraíodh na tagairtí acadúla i gcoinne na bhfoinsí a luaitear — tá a nasc DOI féin ag gach iontráil.',
      'Gineadh na haistriúcháin le IS agus chuaigh siad trí thrí bhabhta profléitheoireachta.',
      '<strong>Cén fáth é seo a nochtadh?</strong> Ar mhaithe le comhsheasmhacht le treoir Eitice agus RGCS an lámhleabhair féin: is í an trédhearcacht faoi úsáid IS go díreach a mholann Farol do mhúinteoirí.',
      'Acmhainn faisnéise é Farol, ní treoir chliniciúil: baineann sainaithint agus diagnóis le gairmithe cáilithe.',
    ],
    etica: 'Féach freisin',
  },
  mt: {
    title: 'Kif sar',
    cat: 'Trasparenza',
    subtitle: 'Direzzjoni umana, għajnuna tal-IA, verifika u reviżjoni — min għamel xiex.',
    desc: 'Trasparenza dwar kif sar Farol: direzzjoni umana, għajnuna tal-IA, verifika tas-sorsi u reviżjoni.',
    items: [
      '<strong>Konċezzjoni, direzzjoni u struttura pedagoġika:</strong> Guilherme de Góis Machado.',
      'Il-kontenut tfassal bl-għajnuna tal-IA (Claude, ta’ Anthropic) taħt id-direzzjoni tal-awtur, b’reviżjoni umana ta’ kull karta.',
      'Ir-referenzi akkademiċi ġew verifikati mas-sorsi ċċitati — kull waħda għandha l-link DOI tagħha.',
      'It-traduzzjonijiet ġew iġġenerati bl-IA u għaddew minn tliet rawnds ta’ reviżjoni.',
      '<strong>Għaliex niddikjarawh?</strong> Għal koerenza mal-gwida tal-Etika u l-GDPR tal-manwal stess: it-trasparenza dwar l-użu tal-IA hija eżattament dak li Farol jirrakkomanda lill-għalliema.',
      'Farol huwa riżors informattiv, mhux gwida klinika: l-identifikazzjoni u d-dijanjożi jappartjenu lil professjonisti kkwalifikati.',
    ],
    etica: 'Ara wkoll',
  },
};

// hreflang / footer hrefs for the transparency page (PT slug at root, shared
// English slug under each language prefix — same convention as sobre/about).
export function allMadeHrefs(base: string): Record<Lang, string> {
  const out = {} as Record<Lang, string>;
  const langs: Lang[] = ['pt','en','es','fr','it','hr','de','nl','pl','ro','cs','sv','da','fi','sk','el','hu','bg','lt','lv','et','sl','ga','mt'];
  for (const l of langs) out[l] = l === 'pt' ? `${base}como-foi-feito/` : `${base}${l}/how-it-was-made/`;
  return out;
}
