// Observation-first entry: teachers reason from what they SEE in the room, not
// from a diagnostic label. Each observation is a plain classroom description that
// routes to the relevant profile card. The profile mapping is language-independent;
// only `text` is localized. Two observations per profile, phrased non-clinically.
import type { Lang } from './i18n';

export interface Observation {
  profile: string;
  text: Record<Lang, string>;
}

export const observations: Observation[] = [
  { profile: 'tdah', text: {
    pt: 'Não para quieto, interrompe, distrai-se com tudo',
    en: 'Can\'t sit still, interrupts, distracted by everything',
    es: 'No se está quieto, interrumpe, se distrae con todo',
    fr: 'Ne tient pas en place, coupe la parole, tout le distrait',
    it: 'Non sta fermo, interrompe, si distrae per ogni cosa',
    hr: 'Ne može mirno sjediti, upada u riječ, sve ga ometa',
    de: 'Kann nicht stillsitzen, unterbricht, von allem ablenkbar',
    nl: 'Kan niet stilzitten, onderbreekt, door alles afgeleid',
    pl: 'Nie usiedzi w miejscu, przerywa, rozprasza się byle czym',
    ro: 'Nu stă locului, întrerupe, e distras de orice',
    cs: 'Neposedí, skáče do řeči, rozptýlí ho cokoli',
    sv: 'Kan inte sitta still, avbryter, distraheras av allt',
    da: 'Kan ikke sidde stille, afbryder, distraheres af alt',
    fi: 'Ei pysy paikallaan, keskeyttää, häiriintyy kaikesta',
    sk: 'Neposedí, skáče do reči, rozptýli ho hocičo',
    el: 'Δεν κάθεται ήσυχα, διακόπτει, αποσπάται από τα πάντα',
    hu: 'Nem tud nyugton maradni, közbevág, minden elvonja a figyelmét',
    bg: 'Не се задържа на място, прекъсва, всичко го разсейва',
    lt: 'Nenustygsta vietoje, pertraukinėja, viskas jį blaško',
    lv: 'Nespēj nosēdēt mierā, pārtrauc, viss novērš uzmanību',
    et: 'Ei püsi paigal, segab vahele, kõik hajutab tähelepanu',
    sl: 'Ne obsedi pri miru, prekinja, vse ga zmoti',
    ga: 'Ní féidir leis suí socair, briseann isteach, gach rud ag cur as dó',
    mt: 'Ma joqgħodx kwiet, jinterrompi, kollox itellfu',
    tr: 'Yerinde duramaz, sözü keser, her şeyle dikkati dağılır',
    no: 'Sitter ikke stille, avbryter, blir avledet av alt',
  }},
  { profile: 'tdah', text: {
    pt: 'Esquece instruções, perde o material, não acaba tarefas',
    en: 'Forgets instructions, loses materials, doesn\'t finish tasks',
    es: 'Olvida las instrucciones, pierde el material, no termina las tareas',
    fr: 'Oublie les consignes, perd ses affaires, ne finit pas son travail',
    it: 'Dimentica le consegne, perde il materiale, non finisce i compiti',
    hr: 'Zaboravlja upute, gubi pribor, ne dovršava zadatke',
    de: 'Vergisst Anweisungen, verliert Material, macht Aufgaben nicht fertig',
    nl: 'Vergeet instructies, raakt spullen kwijt, maakt taken niet af',
    pl: 'Zapomina poleceń, gubi przybory, nie kończy zadań',
    ro: 'Uită instrucțiunile, își pierde lucrurile, nu termină sarcinile',
    cs: 'Zapomíná pokyny, ztrácí pomůcky, nedokončuje úkoly',
    sv: 'Glömmer instruktioner, tappar bort saker, gör inte klart uppgifter',
    da: 'Glemmer beskeder, mister sine ting, gør ikke opgaver færdige',
    fi: 'Unohtaa ohjeet, hukkaa tavaransa, jättää tehtävät kesken',
    sk: 'Zabúda pokyny, stráca pomôcky, nedokončuje úlohy',
    el: 'Ξεχνά τις οδηγίες, χάνει τα υλικά του, δεν ολοκληρώνει τις εργασίες',
    hu: 'Elfelejti az utasításokat, elhagyja a holmiját, nem fejezi be a feladatokat',
    bg: 'Забравя инструкциите, губи материали, не довършва задачите',
    lt: 'Pamiršta nurodymus, pameta daiktus, nebaigia užduočių',
    lv: 'Aizmirst norādījumus, pazaudē mantas, nepabeidz darbu',
    et: 'Unustab juhised, kaotab asju, ei vii ülesandeid lõpuni',
    sl: 'Pozablja navodila, izgublja pripomočke, ne dokonča nalog',
    ga: 'Déanann dearmad ar threoracha, cailleann a chuid ábhar, ní chríochnaíonn tascanna',
    mt: 'Jinsa l-istruzzjonijiet, jitlef l-affarijiet tiegħu, ma jlestix ix-xogħol',
    tr: 'Ödevlerini unutur, çantası ve masası dağınık',
    no: 'Glemmer leksene, sekken og pulten er rotete',
  }},
  { profile: 'dislexia', text: {
    pt: 'Evita ler em voz alta, lê devagar e com esforço',
    en: 'Avoids reading aloud, reads slowly and with effort',
    es: 'Evita leer en voz alta, lee despacio y con esfuerzo',
    fr: 'Évite de lire à voix haute, lit lentement et avec effort',
    it: 'Evita di leggere ad alta voce, legge lentamente e con fatica',
    hr: 'Izbjegava čitanje naglas, čita sporo i s naporom',
    de: 'Vermeidet lautes Vorlesen, liest langsam und mühsam',
    nl: 'Vermijdt hardop lezen, leest traag en met moeite',
    pl: 'Unika czytania na głos, czyta wolno i z trudem',
    ro: 'Evită cititul cu voce tare, citește greu și încet',
    cs: 'Vyhýbá se čtení nahlas, čte pomalu a s námahou',
    sv: 'Undviker att läsa högt, läser långsamt och mödosamt',
    da: 'Undgår at læse højt, læser langsomt og besværet',
    fi: 'Välttää ääneen lukemista, lukee hitaasti ja työläästi',
    sk: 'Vyhýba sa čítaniu nahlas, číta pomaly a s námahou',
    el: 'Αποφεύγει να διαβάζει φωναχτά, διαβάζει αργά και με κόπο',
    hu: 'Kerüli a hangos olvasást, lassan és nehezen olvas',
    bg: 'Избягва четенето на глас, чете бавно и с усилие',
    lt: 'Vengia skaityti balsu, skaito lėtai ir sunkiai',
    lv: 'Izvairās lasīt skaļi, lasa lēni un ar piepūli',
    et: 'Väldib valjusti lugemist, loeb aeglaselt ja vaevaliselt',
    sl: 'Izogiba se glasnemu branju, bere počasi in z naporom',
    ga: 'Seachnaíonn léamh os ard, léann go mall agus le stró',
    mt: 'Jevita li jaqra b\'leħen għoli, jaqra bil-mod u bi sforz',
    tr: 'Sesli okumaktan kaçınır, harfleri karıştırır, yavaş okur',
    no: 'Unngår å lese høyt, blander bokstaver, leser sakte',
  }},
  { profile: 'dislexia', text: {
    pt: 'Troca letras, escreve muito abaixo do que fala',
    en: 'Reverses letters, writes far below how they speak',
    es: 'Confunde letras, escribe mucho peor de lo que habla',
    fr: 'Inverse les lettres, écrit bien en dessous de son niveau à l’oral',
    it: 'Inverte le lettere, scrive molto peggio di come parla',
    hr: 'Zamjenjuje slova, piše puno lošije nego što govori',
    de: 'Verwechselt Buchstaben, schreibt weit unter dem Sprachniveau',
    nl: 'Verwisselt letters, schrijft ver onder spreekniveau',
    pl: 'Myli litery, pisze dużo gorzej, niż mówi',
    ro: 'Confundă literele, scrie mult sub nivelul la care vorbește',
    cs: 'Zaměňuje písmena, píše mnohem hůř, než mluví',
    sv: 'Kastar om bokstäver, skriver långt under hur hen talar',
    da: 'Bytter om på bogstaver, skriver langt under sit mundtlige niveau',
    fi: 'Sekoittaa kirjaimet, kirjoittaa paljon heikommin kuin puhuu',
    sk: 'Zamieňa písmená, píše oveľa horšie, než rozpráva',
    el: 'Μπερδεύει τα γράμματα, γράφει πολύ χειρότερα απ\' ό,τι μιλά',
    hu: 'Felcseréli a betűket, sokkal gyengébben ír, mint ahogy beszél',
    bg: 'Разменя буквите, пише много под нивото, на което говори',
    lt: 'Sukeičia raides, rašo daug prasčiau, nei kalba',
    lv: 'Jauc burtus, raksta daudz vājāk, nekā runā',
    et: 'Ajab tähed segi, kirjutab palju kehvemini, kui räägib',
    sl: 'Zamenjuje črke, piše veliko slabše, kot govori',
    ga: 'Aisiompaíonn litreacha, scríobhann i bhfad faoi bhun a chuid cainte',
    mt: 'Jaqleb l-ittri, jikteb ferm agħar milli jitkellem',
    tr: 'Yazarken çok hata yapar ama sözlü anlatınca fikirleri açık',
    no: 'Gjør mange feil når hun skriver, men forklarer klart muntlig',
  }},
  { profile: 'dispraxia', text: {
    pt: 'Desajeitado, letra difícil, muito desorganizado',
    en: 'Clumsy, messy handwriting, very disorganised',
    es: 'Torpe, letra desordenada, muy desorganizado',
    fr: 'Maladroit, écriture brouillonne, très désorganisé',
    it: 'Goffo, calligrafia disordinata, molto disorganizzato',
    hr: 'Nespretan, neuredan rukopis, vrlo neorganiziran',
    de: 'Ungeschickt, unleserliche Handschrift, sehr unorganisiert',
    nl: 'Onhandig, slordig handschrift, erg ongeorganiseerd',
    pl: 'Niezdarny, niechlujne pismo, bardzo niezorganizowany',
    ro: 'Neîndemânatic, scris dezordonat, foarte dezorganizat',
    cs: 'Nešikovný, nečitelné písmo, velmi neuspořádaný',
    sv: 'Klumpig, rörig handstil, mycket oordnad',
    da: 'Kluntet, rodet håndskrift, meget uorganiseret',
    fi: 'Kömpelö, epäselvä käsiala, hyvin epäjärjestelmällinen',
    sk: 'Nešikovný, nečitateľné písmo, veľmi neusporiadaný',
    el: 'Αδέξιος, ακατάστατος γραφικός χαρακτήρας, πολύ ανοργάνωτος',
    hu: 'Ügyetlen, rendezetlen kézírás, nagyon szervezetlen',
    bg: 'Непохватен, нечетлив почерк, много неорганизиран',
    lt: 'Nevikrus, netvarkingas raštas, labai neorganizuotas',
    lv: 'Neveikls, nekārtīgs rokraksts, ļoti neorganizēts',
    et: 'Kohmakas, loetamatu käekiri, väga korratu',
    sl: 'Neroden, nečitljiva pisava, zelo neurejen',
    ga: 'Ciotach, lámhscríbhneoireacht mhíshlachtmhar, an-mhí-eagraithe',
    mt: 'Goff, kitba mħarbta, diżorganizzat ħafna',
    tr: 'Sakar görünür, sık sık bir şey düşürür, elyazısı zor okunur',
    no: 'Virker klossete, mister ting ofte, håndskriften er vanskelig å lese',
  }},
  { profile: 'dispraxia', text: {
    pt: 'Perde-se em tarefas com passos e sequências',
    en: 'Gets lost in tasks with steps and sequences',
    es: 'Se pierde en las tareas de varios pasos',
    fr: 'Se perd dans les tâches en plusieurs étapes',
    it: 'Si perde nei compiti con più passaggi in sequenza',
    hr: 'Izgubi se u zadacima s više koraka i redoslijedom',
    de: 'Verliert den Faden bei mehrschrittigen Aufgaben',
    nl: 'Raakt de draad kwijt bij taken met meerdere stappen',
    pl: 'Gubi się w zadaniach z wieloma krokami i kolejnością',
    ro: 'Se pierde în sarcinile cu pași și secvențe',
    cs: 'Ztrácí se v úkolech s více kroky a postupy',
    sv: 'Tappar tråden i uppgifter med steg och ordningsföljd',
    da: 'Mister tråden i opgaver med trin og rækkefølge',
    fi: 'Eksyy tehtävissä, joissa on vaiheita ja järjestystä',
    sk: 'Stráca sa v úlohách s viacerými krokmi a postupmi',
    el: 'Χάνεται σε εργασίες με βήματα και σειρά',
    hu: 'Elveszik a többlépéses, sorrendet igénylő feladatokban',
    bg: 'Обърква се при задачи със стъпки и последователност',
    lt: 'Pasimeta užduotyse su keliais žingsniais ir seka',
    lv: 'Apjūk uzdevumos ar vairākiem soļiem un secību',
    et: 'Läheb segadusse ülesannetes, kus on mitu sammu',
    sl: 'Izgubi se pri nalogah z več koraki in zaporedji',
    ga: 'Téann amú i dtascanna a bhfuil céimeanna agus seichimh iontu',
    mt: 'Jintilef f\'xogħol b\'passi u sekwenzi',
    tr: 'Ayakkabı bağlamak ya da cetvel kullanmak gibi işlerde zorlanır',
    no: 'Strever med knyting av sko eller bruk av linjal',
  }},
  { profile: 'autismo', text: {
    pt: 'Perturba-se com ruído ou mudanças de rotina',
    en: 'Distressed by noise or changes in routine',
    es: 'Le angustian el ruido o los cambios de rutina',
    fr: 'Angoissé par le bruit ou les changements de routine',
    it: 'Va in difficoltà con i rumori o i cambi di routine',
    hr: 'Uznemiruje ga buka ili promjene rutine',
    de: 'Belastet durch Lärm oder Veränderungen im Ablauf',
    nl: 'Van slag door lawaai of veranderingen in de routine',
    pl: 'Źle znosi hałas i zmiany w rutynie',
    ro: 'Tulburat de zgomot sau de schimbările de rutină',
    cs: 'Špatně snáší hluk a změny zaběhnutého režimu',
    sv: 'Tar illa vid sig av oljud eller förändringar i rutinen',
    da: 'Bliver oprevet over støj eller ændringer i rutinen',
    fi: 'Ahdistuu melusta tai rutiinien muutoksista',
    sk: 'Zle znáša hluk a zmeny v zabehnutom režime',
    el: 'Αναστατώνεται από τον θόρυβο ή τις αλλαγές στη ρουτίνα',
    hu: 'Megviseli a zaj vagy a megszokott rend változása',
    bg: 'Тревожи се от шум или промени в рутината',
    lt: 'Nerimą kelia triukšmas ar dienotvarkės pokyčiai',
    lv: 'Satrauc troksnis vai izmaiņas ikdienā',
    et: 'Müra või rutiini muutused tekitavad ärevust',
    sl: 'Vznemirja ga hrup ali spremembe rutine',
    ga: 'Cráite ag torann nó ag athruithe ar an ngnáthamh',
    mt: 'Jinkwieta bil-ħsejjes jew bit-tibdil fir-rutina',
    tr: 'Göz teması kurmaz, rutin değişince altüst olur',
    no: 'Unngår blikkontakt, blir ute av seg når rutinen endres',
  }},
  { profile: 'autismo', text: {
    pt: 'Muito literal, não capta o que fica por dizer',
    en: 'Very literal, misses what\'s left unsaid',
    es: 'Muy literal, no capta lo que no se dice',
    fr: 'Très littéral, ne saisit pas le non-dit',
    it: 'Molto letterale, non coglie il non detto',
    hr: 'Vrlo doslovan, ne shvaća ono neizrečeno',
    de: 'Sehr wörtlich, versteht Zwischentöne nicht',
    nl: 'Erg letterlijk, mist wat onuitgesproken blijft',
    pl: 'Rozumie wszystko dosłownie, nie wyłapuje niedopowiedzeń',
    ro: 'Foarte literal, nu prinde ce nu se spune',
    cs: 'Bere všechno doslova, nevnímá nevyřčené',
    sv: 'Mycket bokstavlig, missar det som inte sägs',
    da: 'Meget bogstavelig, overser det, der ikke bliver sagt',
    fi: 'Ymmärtää kirjaimellisesti, ei huomaa sanomatta jäänyttä',
    sk: 'Berie všetko doslova, nevníma nevyslovené',
    el: 'Πολύ κυριολεκτικός, δεν πιάνει τα υπονοούμενα',
    hu: 'Mindent szó szerint ért, nem érzékeli a ki nem mondottat',
    bg: 'Много буквален, не долавя неизказаното',
    lt: 'Viską supranta pažodžiui, nesuvokia to, kas nepasakyta',
    lv: 'Ļoti burtisks, nesaprot neizteikto',
    et: 'Väga sõnasõnaline, ei taju ütlemata jäetut',
    sl: 'Vse razume dobesedno, ne zazna neizrečenega',
    ga: 'An-liteartha, ní thuigeann an rud nach ndeirtear',
    mt: 'Litterali ħafna, ma jindunax b\'dak li ma jingħadx',
    tr: 'Bir konuyu olağanüstü ayrıntıda anlatır, gürültüden rahatsız olur',
    no: 'Forteller om ett tema i uvanlig detalj, plages av støy',
  }},
  { profile: 'sobredotacao', text: {
    pt: 'Acaba tudo depressa, aborrece-se e perturba',
    en: 'Finishes everything fast, gets bored and disruptive',
    es: 'Termina todo rápido, se aburre y molesta',
    fr: 'Finit tout très vite, s\'ennuie et perturbe la classe',
    it: 'Finisce tutto in fretta, si annoia e disturba',
    hr: 'Sve brzo završi, dosađuje se i ometa nastavu',
    de: 'Ist mit allem schnell fertig, langweilt sich und stört',
    nl: 'Snel klaar met alles, verveelt zich en stoort',
    pl: 'Kończy wszystko szybko, nudzi się i przeszkadza',
    ro: 'Termină totul repede, se plictisește și deranjează',
    cs: 'Vše dokončí rychle, nudí se a vyrušuje',
    sv: 'Blir snabbt klar med allt, blir uttråkad och stökig',
    da: 'Bliver hurtigt færdig med alt, keder sig og forstyrrer',
    fi: 'Tekee kaiken nopeasti, kyllästyy ja häiriköi',
    sk: 'Všetko dokončí rýchlo, nudí sa a vyrušuje',
    el: 'Τα τελειώνει όλα γρήγορα, βαριέται και ενοχλεί',
    hu: 'Mindent gyorsan befejez, unatkozik és zavarja az órát',
    bg: 'Свършва всичко бързо, отегчава се и пречи',
    lt: 'Viską greitai padaro, nuobodžiauja ir trukdo',
    lv: 'Visu ātri pabeidz, garlaikojas un traucē',
    et: 'Teeb kõik kiiresti valmis, tüdineb ja segab tundi',
    sl: 'Vse hitro konča, se dolgočasi in moti pouk',
    ga: 'Críochnaíonn gach rud go tapa, tagann leadrán air agus cuireann sé isteach ar an rang',
    mt: 'Ilesti kollox malajr, jiddejjaq u jfixkel il-klassi',
    tr: 'Her şeyi çabuk bitirir, sıkılır, ders bölmeye başlar',
    no: 'Blir fort ferdig, kjeder seg, begynner å forstyrre',
  }},
  { profile: 'sobredotacao', text: {
    pt: 'Muito capaz, mas com notas abaixo do esperado',
    en: 'Clearly able, but underperforming',
    es: 'Claramente capaz, pero rinde por debajo',
    fr: 'Manifestement capable, mais en sous-performance',
    it: 'Chiaramente capace, ma rende poco',
    hr: 'Očito sposoban, ali postiže ispod svojih mogućnosti',
    de: 'Deutlich fähig, bleibt aber unter seinen Möglichkeiten',
    nl: 'Duidelijk capabel, maar presteert onder niveau',
    pl: 'Wyraźnie zdolny, ale osiąga poniżej możliwości',
    ro: 'Evident capabil, dar cu rezultate slabe',
    cs: 'Zjevně nadaný, ale nevyužívá svůj potenciál',
    sv: 'Tydligt kapabel, men presterar under sin förmåga',
    da: 'Tydeligt dygtig, men præsterer under evne',
    fi: 'Selvästi kyvykäs, mutta alisuoriutuu',
    sk: 'Zjavne nadaný, ale nevyužíva svoj potenciál',
    el: 'Σαφώς ικανός, αλλά αποδίδει κάτω από τις δυνατότητές του',
    hu: 'Nyilvánvalóan tehetséges, mégis alulteljesít',
    bg: 'Явно способен, но постига под възможностите си',
    lt: 'Aiškiai gabus, bet nepasiekia savo galimybių',
    lv: 'Nepārprotami spējīgs, bet sniegums zem iespējām',
    et: 'Selgelt võimekas, kuid jääb oma võimetele alla',
    sl: 'Očitno sposoben, a dosega manj, kot zmore',
    ga: 'Cumasach go soiléir, ach ag feidhmiú faoi bhun a chumais',
    mt: 'Kapaċi biċ-ċar, imma qed jirrendi inqas milli jista\'',
    tr: 'Yaşına göre şaşırtıcı sorular sorar ama ödevini teslim etmez',
    no: 'Stiller overraskende spørsmål for alderen, men leverer ikke oppgavene',
  }},
  { profile: 'plnm', text: {
    pt: 'Acabou de chegar, ainda não fala a língua de ensino',
    en: 'Just arrived, doesn\'t yet speak the language of instruction',
    es: 'Recién llegado, aún no habla el idioma de clase',
    fr: 'Vient d\'arriver, ne parle pas encore la langue de la classe',
    it: 'Appena arrivato, non parla ancora la lingua della classe',
    hr: 'Tek je stigao, još ne govori jezik nastave',
    de: 'Neu angekommen, spricht die Unterrichtssprache noch nicht',
    nl: 'Net aangekomen, spreekt de instructietaal nog niet',
    pl: 'Dopiero przyjechał, nie mówi jeszcze w języku nauczania',
    ro: 'Abia sosit, nu vorbește încă limba de predare',
    cs: 'Právě přišel, ještě nemluví vyučovacím jazykem',
    sv: 'Nyanländ, talar ännu inte undervisningsspråket',
    da: 'Netop ankommet, taler endnu ikke undervisningssproget',
    fi: 'Vasta saapunut, ei vielä puhu opetuskieltä',
    sk: 'Práve prišiel, ešte nehovorí vyučovacím jazykom',
    el: 'Μόλις έφτασε, δεν μιλά ακόμη τη γλώσσα διδασκαλίας',
    hu: 'Most érkezett, még nem beszéli az oktatás nyelvét',
    bg: 'Току-що пристигна, още не говори езика на обучение',
    lt: 'Ką tik atvyko, dar nekalba mokymo kalba',
    lv: 'Tikko ieradies, vēl nerunā mācību valodā',
    et: 'Äsja saabunud, ei räägi veel õppekeelt',
    sl: 'Pravkar je prišel, še ne govori učnega jezika',
    ga: 'Díreach tagtha, gan teanga an teagaisc aige fós',
    mt: 'Għadu kif wasal, għadu ma jitkellimx bil-lingwa tat-tagħlim',
    tr: 'Anlıyor gibi görünüyor ama yazılıda bir şey yazamıyor',
    no: 'Ser ut til å forstå, men får ikke skrevet noe på prøven',
  }},
  { profile: 'plnm', text: {
    pt: 'Percebe mais do que consegue dizer na língua da escola',
    en: 'Understands more than they can say in the school language',
    es: 'Entiende más de lo que sabe decir en el idioma de la escuela',
    fr: 'Comprend plus qu\'il ne peut dire dans la langue de l\'école',
    it: 'Capisce più di quanto riesca a dire nella lingua della scuola',
    hr: 'Razumije više nego što može reći na jeziku škole',
    de: 'Versteht mehr, als er oder sie in der Schulsprache ausdrücken kann',
    nl: 'Begrijpt meer dan hij of zij in de schooltaal kan zeggen',
    pl: 'Rozumie więcej, niż potrafi powiedzieć w języku szkoły',
    ro: 'Înțelege mai mult decât poate spune în limba școlii',
    cs: 'Rozumí víc, než dokáže říct školním jazykem',
    sv: 'Förstår mer än hen kan uttrycka på skolspråket',
    da: 'Forstår mere, end eleven kan sige på skolesproget',
    fi: 'Ymmärtää enemmän kuin osaa sanoa koulukielellä',
    sk: 'Rozumie viac, než dokáže povedať školským jazykom',
    el: 'Καταλαβαίνει περισσότερα απ\' όσα μπορεί να πει στη σχολική γλώσσα',
    hu: 'Többet ért, mint amennyit az iskola nyelvén ki tud mondani',
    bg: 'Разбира повече, отколкото може да каже на училищния език',
    lt: 'Supranta daugiau, nei gali pasakyti mokyklos kalba',
    lv: 'Saprot vairāk, nekā spēj pateikt skolas valodā',
    et: 'Saab rohkem aru, kui oskab koolikeeles öelda',
    sl: 'Razume več, kot zmore povedati v šolskem jeziku',
    ga: 'Tuigeann níos mó ná mar is féidir leis a rá i dteanga na scoile',
    mt: 'Jifhem aktar milli kapaċi jgħid bil-lingwa tal-iskola',
    tr: 'Sınıfta sessiz, teneffüste kendi dilinde akıcı konuşuyor',
    no: 'Stille i klassen, snakker flytende sitt eget språk i friminuttet',
  }},
  { profile: 'discalculia', text: {
    pt: 'Conta pelos dedos quando os colegas já calculam de cor',
    en: 'Counts on their fingers when classmates already calculate from memory',
    es: 'Cuenta con los dedos cuando sus compañeros ya calculan de memoria',
    fr: 'Compte sur ses doigts quand les autres calculent déjà de tête',
    it: 'Conta sulle dita quando i compagni calcolano già a mente',
    hr: 'Broji na prste dok vršnjaci već računaju napamet',
    de: 'Zählt an den Fingern, wenn andere längst im Kopf rechnen',
    nl: 'Telt op de vingers terwijl klasgenoten al uit het hoofd rekenen',
    pl: 'Liczy na palcach, gdy rówieśnicy liczą już w pamięci',
    ro: 'Numără pe degete când colegii calculează deja în minte',
    cs: 'Počítá na prstech, když spolužáci už počítají zpaměti',
    sv: 'Räknar på fingrarna när klasskamraterna redan räknar i huvudet',
    da: 'Tæller på fingrene, når klassekammeraterne allerede regner i hovedet',
    fi: 'Laskee sormilla, kun luokkakaverit laskevat jo päässään',
    sk: 'Počíta na prstoch, keď spolužiaci už počítajú spamäti',
    el: 'Μετρά με τα δάχτυλα ενώ οι συμμαθητές υπολογίζουν ήδη από μνήμης',
    hu: 'Az ujjain számol, amikor társai már fejben számolnak',
    bg: 'Брои на пръсти, когато съучениците вече смятат наум',
    lt: 'Skaičiuoja pirštais, kai bendraklasiai jau skaičiuoja mintinai',
    lv: 'Skaita uz pirkstiem, kad klasesbiedri jau rēķina galvā',
    et: 'Loeb sõrmedel, kui klassikaaslased arvutavad juba peast',
    sl: 'Šteje na prste, ko sošolci že računajo na pamet',
    ga: 'Comhaireamh ar na méara nuair a bhíonn a chomhscoláirí ag ríomh de ghlanmheabhair cheana',
    mt: 'Jgħodd fuq subgħajh meta sħabu diġà jikkalkulaw f’moħħhom',
    tr: 'Sayıları karşılaştırmakta zorlanır, hâlâ parmakla sayar',
    no: 'Strever med å sammenligne tall, teller fortsatt på fingrene',
  }},
  { profile: 'discalculia', text: {
    pt: 'Sabe raciocinar, mas troca números e esquece as tabuadas',
    en: 'Reasons well, but mixes up numbers and forgets times tables',
    es: 'Razona bien, pero confunde números y olvida las tablas',
    fr: 'Raisonne bien, mais confond les nombres et oublie les tables',
    it: 'Ragiona bene, ma confonde i numeri e dimentica le tabelline',
    hr: 'Dobro rasuđuje, ali brka brojeve i zaboravlja tablicu množenja',
    de: 'Denkt gut mit, verwechselt aber Zahlen und vergisst das Einmaleins',
    nl: 'Redeneert goed, maar haalt getallen door elkaar en vergeet de tafels',
    pl: 'Dobrze rozumuje, ale myli liczby i zapomina tabliczkę mnożenia',
    ro: 'Raționează bine, dar încurcă numerele și uită tabla înmulțirii',
    cs: 'Uvažuje dobře, ale plete si čísla a zapomíná malou násobilku',
    sv: 'Resonerar bra men blandar ihop siffror och glömmer multiplikationstabellen',
    da: 'Ræsonnerer godt, men bytter om på tal og glemmer tabellerne',
    fi: 'Päättelee hyvin, mutta sekoittaa numerot ja unohtaa kertotaulut',
    sk: 'Uvažuje dobre, ale pletie si čísla a zabúda malú násobilku',
    el: 'Σκέφτεται καλά, αλλά μπερδεύει τους αριθμούς και ξεχνά την προπαίδεια',
    hu: 'Jól gondolkodik, de összekeveri a számokat és elfelejti a szorzótáblát',
    bg: 'Разсъждава добре, но обърква числата и забравя таблицата за умножение',
    lt: 'Gerai mąsto, bet painioja skaičius ir pamiršta daugybos lentelę',
    lv: 'Labi spriež, bet jauc skaitļus un aizmirst reizrēķinu',
    et: 'Arutleb hästi, kuid ajab arvud segamini ja unustab korrutustabeli',
    sl: 'Dobro sklepa, a zamenjuje števila in pozablja poštevanko',
    ga: 'Réasúnaíonn go maith, ach meascann uimhreacha agus déanann dearmad ar na táblaí',
    mt: 'Jirraġuna tajjeb, imma jħawwad in-numri u jinsa l-multiplikazzjonijiet',
    tr: 'Çarpım tablosunu tekrar tekrar çalışsa da aklında tutamaz',
    no: 'Husker ikke gangetabellen tross gjentatt øving',
  }},
];

// Resolve an observation's text for a language, falling back to English then
// Portuguese so a missing translation never renders blank.
export function obsText(o: Observation, lang: Lang): string {
  return o.text[lang] ?? o.text.en ?? o.text.pt ?? '';
}

// Homepage grouping: twelve identical-looking chips read as a wall, so they are
// presented under three scannable themes. Each theme covers exactly two profiles;
// the grouping is a navigation heuristic, not a clinical taxonomy.
export interface ObservationTheme {
  key: string;
  profiles: string[];
  label: Record<Lang, string>;
}

export const obsThemes: ObservationTheme[] = [
  { key: 'focus', profiles: ['tdah', 'sobredotacao'], label: {
    pt: 'Atenção, ritmo e comportamento',
    en: 'Attention, pace and behaviour',
    es: 'Atención, ritmo y comportamiento',
    fr: 'Attention, rythme et comportement',
    it: 'Attenzione, ritmo e comportamento',
    hr: 'Pažnja, tempo i ponašanje',
    de: 'Aufmerksamkeit, Tempo und Verhalten',
    nl: 'Aandacht, tempo en gedrag',
    pl: 'Uwaga, tempo i zachowanie',
    ro: 'Atenție, ritm și comportament',
    cs: 'Pozornost, tempo a chování',
    sv: 'Uppmärksamhet, tempo och beteende',
    da: 'Opmærksomhed, tempo og adfærd',
    fi: 'Tarkkaavaisuus, tahti ja käyttäytyminen',
    sk: 'Pozornosť, tempo a správanie',
    el: 'Προσοχή, ρυθμός και συμπεριφορά',
    hu: 'Figyelem, tempó és viselkedés',
    bg: 'Внимание, темпо и поведение',
    lt: 'Dėmesys, tempas ir elgesys',
    lv: 'Uzmanība, temps un uzvedība',
    et: 'Tähelepanu, tempo ja käitumine',
    sl: 'Pozornost, tempo in vedenje',
    ga: 'Aird, luas agus iompar',
    mt: 'Attenzjoni, ritmu u mġiba',
    tr: 'Dikkat ve tempo',
    no: 'Oppmerksomhet og tempo',
  }},
  { key: 'written', profiles: ['dislexia', 'dispraxia', 'discalculia'], label: {
    pt: 'Leitura, escrita e organização',
    en: 'Reading, writing and organisation',
    es: 'Lectura, escritura y organización',
    fr: 'Lecture, écriture et organisation',
    it: 'Lettura, scrittura e organizzazione',
    hr: 'Čitanje, pisanje i organizacija',
    de: 'Lesen, Schreiben und Organisation',
    nl: 'Lezen, schrijven en organisatie',
    pl: 'Czytanie, pisanie i organizacja',
    ro: 'Citit, scris și organizare',
    cs: 'Čtení, psaní a organizace',
    sv: 'Läsning, skrivning och organisation',
    da: 'Læsning, skrivning og organisering',
    fi: 'Lukeminen, kirjoittaminen ja organisointi',
    sk: 'Čítanie, písanie a organizácia',
    el: 'Ανάγνωση, γραφή και οργάνωση',
    hu: 'Olvasás, írás és szervezettség',
    bg: 'Четене, писане и организация',
    lt: 'Skaitymas, rašymas ir organizuotumas',
    lv: 'Lasīšana, rakstīšana un organizētība',
    et: 'Lugemine, kirjutamine ja organiseeritus',
    sl: 'Branje, pisanje in organiziranost',
    ga: 'Léitheoireacht, scríbhneoireacht agus eagrúchán',
    mt: 'Qari, kitba u organizzazzjoni',
    tr: 'Okuma ve yazma',
    no: 'Lesing og skriving',
  }},
  { key: 'language', profiles: ['autismo', 'plnm'], label: {
    pt: 'Comunicação e língua',
    en: 'Communication and language',
    es: 'Comunicación y lengua',
    fr: 'Communication et langue',
    it: 'Comunicazione e lingua',
    hr: 'Komunikacija i jezik',
    de: 'Kommunikation und Sprache',
    nl: 'Communicatie en taal',
    pl: 'Komunikacja i język',
    ro: 'Comunicare și limbă',
    cs: 'Komunikace a jazyk',
    sv: 'Kommunikation och språk',
    da: 'Kommunikation og sprog',
    fi: 'Vuorovaikutus ja kieli',
    sk: 'Komunikácia a jazyk',
    el: 'Επικοινωνία και γλώσσα',
    hu: 'Kommunikáció és nyelv',
    bg: 'Комуникация и език',
    lt: 'Bendravimas ir kalba',
    lv: 'Saziņa un valoda',
    et: 'Suhtlus ja keel',
    sl: 'Komunikacija in jezik',
    ga: 'Cumarsáid agus teanga',
    mt: 'Komunikazzjoni u lingwa',
    tr: 'Dil ve iletişim',
    no: 'Språk og kommunikasjon',
  }},
];
